### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by issacMontes28** [tonysm/laravel-elasticsearch-2019#1]
Thanks in advance for your tutorial, I just downloaded the repository and added laravel vessel for use with the docker elasticsearch image. When I run the command './vessel php artisan search:reindex', I get the error 'no alive nodes found in tour cluster', Do you have any idea of what am I doing wrong? this is my docker-composer.yml

```yaml
version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
     - vesselmysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
  search:
    image: elasticsearch:6.8.1
    environment:
     - "discovery.type=single-node"
     - "bootstrap.memory_lock=true"
    ports:
     - 9200:9200
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"
```

Thanks a lot for your time
